version: '3.1'

volumes:
  certs: ~
  letsencrypt: ~

services:
  nginx:
    image: mozias/nginx:latest
    volumes:
      - certs:/etc/nginx/certs
      - letsencrypt:/data/letsencrypt
    ports:
      - "80:80"
      - "443:443"