version: '3.1'

services:
  mozias_db:
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
  mozias_api:
    ports:
      - "8000:8000"
    environment:
      - ROCKET_ENV=dev
  nginx:
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/mime.types:/etc/nginx/mime.types:ro
      - ./mozias-client/dist:/www/data
