version: '3.1'

volumes:
  certs: ~
  letsencrypt: ~
  moziasdb: ~

services:
  mozias_api:
    image: mozias/mozias-api:latest
    env_file: ./config/api/mozias-api.env
    links:
      - mozias_db
  nginx:
    image: mozias/nginx:latest
    volumes:
      - certs:/etc/nginx/certs
      - letsencrypt:/data/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    links:
      - "mozias_api"
  mozias_db:
    image: mozias/mozias-db:latest
    ports:
      - "3306:3306"
    env_file: ./config/db/mozias-db.env
    volumes:
      - moziasdb:/var/lib/mysql
