#!/usr/bin/python3
import argparse
import os
from os import environ
from subprocess import check_call

# Store the current directory
owd = os.getcwd()

# Setup the supported command-line arguments
parser = argparse.ArgumentParser(description='Push project Docker images')
parser.add_argument('-n', '--nginx', help='Turn off nginx build', action="store_true")
# parser.add_argument('-d', '--dataq', help='Turn off dataq build', action="store_true")

# Parse the command-line arguments
args = parser.parse_args()

# Change working directory
os.chdir(os.path.join(os.path.dirname( __file__ ), '..' ))

if not args.nginx:
  print('Pushing DataQ nginx image')
  check_call(["docker", "push", "mozias/nginx"])

# if not args.dataq:
#   print('Pushing DataQ image')
#   check_call(["docker", "push", "eozias/dataq-api"])

# Change back to the original directory
os.chdir(owd)
